# Generated by Django 4.1.7 on 2023-05-04 16:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('autoservice', '0003_auto_20200518_1240'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='automobilio_modelis',
            options={'verbose_name': 'Automobilio modelis', 'verbose_name_plural': 'Automobilio modeliai'},
        ),
        migrations.AlterModelOptions(
            name='automobilis',
            options={'verbose_name': 'Vehicle', 'verbose_name_plural': 'Vehicles'},
        ),
        migrations.AlterModelOptions(
            name='paslauga',
            options={'verbose_name': 'Paslauga', 'verbose_name_plural': 'Paslaugos'},
        ),
        migrations.AlterModelOptions(
            name='paslaugos_kaina',
            options={'verbose_name': 'Paslaugo kaina', 'verbose_name_plural': 'Paslaugų kainos'},
        ),
        migrations.AlterModelOptions(
            name='uzsakymas',
            options={'verbose_name': 'Užsakymas', 'verbose_name_plural': 'Užsakymai'},
        ),
        migrations.AlterModelOptions(
            name='uzsakymoeilute',
            options={'verbose_name': 'Užsakymo eilutė', 'verbose_name_plural': 'Užsakymo eilutės'},
        ),
        migrations.RemoveField(
            model_name='uzsakymas',
            name='suma',
        ),
        migrations.AddField(
            model_name='automobilis',
            name='aprasymas',
            field=tinymce.models.HTMLField(null=True, verbose_name='Summary'),
        ),
        migrations.AddField(
            model_name='automobilis',
            name='photo',
            field=models.ImageField(null=True, upload_to='autos', verbose_name='Photo'),
        ),
        migrations.AddField(
            model_name='uzsakymas',
            name='grazinimo_laikas',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Gražinimo terminas'),
        ),
        migrations.AddField(
            model_name='uzsakymas',
            name='klientas_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='uzsakymas',
            name='status',
            field=models.CharField(blank=True, choices=[('p', 'Patvirtinta'), ('v', 'Vykdoma'), ('a', 'Atlikta'), ('t', 'Atšaukta')], default='p', help_text='Statusas', max_length=1),
        ),
        migrations.AlterField(
            model_name='automobilis',
            name='automobilio_modelis_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='autoservice.automobilio_modelis', verbose_name='Vehicle'),
        ),
        migrations.AlterField(
            model_name='automobilis',
            name='savininkas',
            field=models.CharField(max_length=200, verbose_name='Owner'),
        ),
        migrations.AlterField(
            model_name='automobilis',
            name='valstybinis_numeris',
            field=models.CharField(max_length=200, verbose_name='Licence plate'),
        ),
        migrations.AlterField(
            model_name='automobilis',
            name='vin_kodas',
            field=models.CharField(max_length=200, verbose_name='VIN code'),
        ),
        migrations.AlterField(
            model_name='paslaugos_kaina',
            name='automobilis_ids',
            field=models.ManyToManyField(to='autoservice.automobilio_modelis'),
        ),
        migrations.AlterField(
            model_name='uzsakymoeilute',
            name='uzsakymas_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eilutes', to='autoservice.uzsakymas'),
        ),
        migrations.CreateModel(
            name='UzsakymoKomentaras',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('komentaras', models.TextField(max_length=2000, verbose_name='Komentaras')),
                ('klientas_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('uzsakymas_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='autoservice.uzsakymas')),
            ],
            options={
                'verbose_name': 'Komentaras',
                'verbose_name_plural': 'Komentarai',
            },
        ),
        migrations.CreateModel(
            name='Profilis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nuotrauka', models.ImageField(default='default.png', upload_to='profile_pics')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Profilis',
                'verbose_name_plural': 'Profiliai',
            },
        ),
    ]
